import { Product } from 'types/product'
import { client } from 'app/api'
import { Products } from 'features/products/Products'
import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { Sidebar } from 'components/Sidebar'
import { Cart } from 'features/Cart/Cart'
import { MAX_ITEMS_PER_PAGE } from 'features/products/productSlice'

type HomeProps = {
  products: Product[]
}

const Home: NextPage<HomeProps> = ({ products }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Sidebar>
        <main className='flex justify-between h-screen overflow-x-hidden p-6'>
          <Products products={products} />
          <Cart />
        </main>
      </Sidebar>
    </div>
  )
}

export async function getStaticPaths() {
  return {
    paths: [
      { params: { page: '1' } },
      { params: { page: '2' } },
      { params: { page: '3' } },
      { params: { page: '4' } },
    ],
    fallback: false, // can also be true or 'blocking'
  }
}

export const getStaticProps: GetStaticProps<
  { products: Product[] },
  { page: string }
> = async (context) => {
  context.params
  // const page = Number(query.page) || 1
  const page = +(context.params?.page ?? 1)
  const limit = page * MAX_ITEMS_PER_PAGE
  const { data: products } = await client<Product[]>('/products', {
    params: { limit: `${limit}` },
  })
  const productForPage = products.slice(limit - MAX_ITEMS_PER_PAGE, limit)

  return { props: { products: productForPage } }
}

export default Home
