name: Development

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build application
    uses: Mooli88/lumigo-e-commerce-app/.github/workflows/build.yml@main

  lint:
    name: Lint
    uses: Mooli88/lumigo-e-commerce-app/.github/workflows/lint.yml@main

  test:
    name: Test application
    uses: Mooli88/lumigo-e-commerce-app/.github/workflows/unit-test.yml@main

     