name: Development

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  workflow_call:
  workflow_dispatch:
    inputs:
      lint_all:
        description: 'Scan entire project for lint errors'
        required: true
        default: true
        type: boolean 
      environment:
        description: 'Environment to run tests against'
        type: environment
        default: 'staging'
        required: true 

jobs:
  build:
    name: Build application
    uses: Mooli88/lumigo-e-commerce-app/.github/workflows/build.yml@main

  lint:
    name: Lint
    uses: Mooli88/lumigo-e-commerce-app/.github/workflows/lint.yml@main
    with:
      lint_all: ${{ inputs.lint_all }}

  test:
    name: Test application
    uses: Mooli88/lumigo-e-commerce-app/.github/workflows/unit-test.yml@main

     