# This workflow will do a clean installation of node dependencies, cache/restore them, and lint check the changed files

name: Linting

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches: ['main']

  workflow_call:
    inputs:
      lint_all:
        type: boolean
        default: false
        required: false

jobs:
  tst:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs.lint_all
        run: echo ${{ inputs.lint_all }}

  lint-changed-files-only:
    runs-on: ubuntu-latest

    if: inputs.lint_all == 'false'

    steps:
      - name: Echo inputs.lint_all
        run: echo ${{ inputs.lint_all }}
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install

      - name: Get file changes
        id: changed_files
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '

      - name: Echo inputs.lint_all
        run: echo ${{ inputs.lint_all }}

      - name: Echo file changes
        run: |
          echo Added files: ${{ steps.changed_files.outputs.files_added }}
          echo Changed files: ${{ steps.changed_files.outputs.files_modified }}
          echo Removed files: ${{ steps.changed_files.outputs.files_removed }}

      - uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
          eslint_flags: -c ./.eslintrc.json --ignore-path ./.eslintignore ${{ steps.changed_files.outputs.files_added }} ${{ steps.changed_files.outputs.files_modified }}
  lint:
    runs-on: ubuntu-latest

    if: inputs.lint_all == 'true'

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install

      - name: Echo inputs.lint_all
        run: echo ${{ inputs.lint_all }}

      - name: Linting
        run: yarn lint